### ISSUE TITLE
Got syntax error invalid regular expression

### ISSUE THREAD

**Issue by chaitanya71998** [zeroturnaround/sql-formatter#213]
Getting the below error for some users, as shown below
```
SyntaxError
Invalid regular expression: /^([\p{Alphabetic}\p{Mark}\p{Decimal_Number}\p{Connector_Punctuation}\p{Join_Control}]+)/: Invalid escape
```
mostly getting in chrome versions and lower version devices
* Chrome Mobile WebView 62.0.3202

How to fix this?

**Comment by nene** [comment]
That's unfortunate. Your Chrome is only a few versions off.

The [regexp unicode property escapes](https://caniuse.com/mdn-javascript_builtins_regexp_property_escapes) are supported since Chrome 64 (released in 2018).

If you use sql-formatter as a library, it should be possible to compile the code to lower target than ES6.

**Comment by nene** [comment]
Closing this, as support for such old browsers is at the very bottom of priorities for now.
