### ISSUE TITLE
help! Formatted little problem with

### ISSUE THREAD

**Issue by AinolaLong** [zeroturnaround/sql-formatter#31]
hi!

i get code like this:

![image](https://user-images.githubusercontent.com/21746104/30330844-c0822db0-9808-11e7-831d-c1de6271f3b3.png)

and i want format to like this:

![image](https://user-images.githubusercontent.com/21746104/30330964-10a0d080-9809-11e7-974c-cf64d6ae1cb3.png)

but i got this: 

![image](https://user-images.githubusercontent.com/21746104/30330991-2846fc1e-9809-11e7-882a-8a3cf9d0a8cb.png)

can you resolve this problem? thanks , i use sql-format "react-router-dom": "^4.1.1",

**Comment by nene** [comment]
So, you would like the formatter to either:

- preserve the original line-breaks in input SQL. Preserving the original formatting is something sql-formatter was not designed to do. So that's a no.
- add four line-breaks between individual SQL statements. Adding four line breaks instead of one looks like a very personal preference. I can imagine somebody else liking the current one, somebody else liking two, but I think very few people would like to have four.

So the only option I see would be to have it configurable. Would that be a solution for you?

**Comment by AinolaLong** [comment]
ok i got it. thank you!
