### ISSUE TITLE
CREATE TABLE statements end up as one long line

### ISSUE THREAD

**Issue by carlbennettnz** [zeroturnaround/sql-formatter#40]
Given this input

```sql
CREATE TABLE items (
  a INT PRIMARY KEY,
  b TEXT
);
```

I'm getting this output

```sql
CREATE TABLE items (a INT PRIMARY KEY, b TEXT);
```

**Comment by nene** [comment]
This is currently by design. sql-formatter will break the parenthesized expression to multiple lines when it's long enough, for example try:

```sql
CREATE TABLE items (a INT PRIMARY KEY, b TEXT, c INT NOT NULL, d INT NOT NULL);
```

Currently though this max-length of parenthesized block is hard-coded to 50 characters. There's an issue #5 for making this configurable. Express your support there if you'd like to have such configurability.
